trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install -g yarn
    yarn
    ng build --prod
  displayName: 'Build and package'
  
- task: CopyFiles@2
  inputs:
    SourceFolder: 'dist/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'